version: "3.8"

x-airflow-common:
  &airflow-common
  build: .
  env_file:
    - .env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./logs:/opt/airflow/logs

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - ./data/sql/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./data/sql/log.sql:/docker-entrypoint-initdb.d/02_log.sql
      - ./data/sql/ignored.sql:/docker-entrypoint-initdb.d/03_ignored.sql


    ports:
      - "5433:5432"

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
      airflow db upgrade &&
      airflow users create
      --username ${_AIRFLOW_WWW_USER_USERNAME}
      --password ${_AIRFLOW_WWW_USER_PASSWORD}
      --firstname admin
      --lastname user
      --role ${_AIRFLOW_WWW_USER_ROLE}
      --email admin@example.com
      "
    depends_on:
      - postgres

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8181:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  grafana:
      image: grafana/grafana:latest
      ports:
        - "3001:3000"
      depends_on:
        - postgres